version: '3.9'

services:
  postgres:
    restart: always
    container_name: blog_postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: blog
      POSTGRES_PASSWORD: blog123
      POSTGRES_DB: blog_db
    ports:
      - "50432:50432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    command: ["postgres", "-c", "port=50432"]

volumes:
  postgres_data: